/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SCHEDULE_PB_H_INCLUDED
#define PB_SCHEDULE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _WeekDay { 
    WeekDay_SUN = 0, 
    WeekDay_MON = 1, 
    WeekDay_TUE = 2, 
    WeekDay_WED = 3, 
    WeekDay_THR = 4, 
    WeekDay_FRI = 5, 
    WeekDay_SAT = 6, 
    WeekDay_EVR = 7 
} WeekDay;

typedef enum _Operation { 
    Operation_OP_NONE = 0, 
    Operation_OP_SKIP = 1, 
    Operation_OP_OPEN = 2, 
    Operation_OP_CLOSE = 3 
} Operation;

/* Struct definitions */
typedef struct _Schedule { 
    int32_t version; 
    pb_callback_t events; 
} Schedule;

typedef struct _ScheduleEntry { 
    bool has_enabled;
    bool enabled; 
    bool has_wday;
    WeekDay wday; 
    bool has_op;
    Operation op; 
    bool has_start_hou;
    int32_t start_hou; 
    bool has_start_min;
    int32_t start_min; 
} ScheduleEntry;


/* Helper constants for enums */
#define _WeekDay_MIN WeekDay_SUN
#define _WeekDay_MAX WeekDay_EVR
#define _WeekDay_ARRAYSIZE ((WeekDay)(WeekDay_EVR+1))

#define _Operation_MIN Operation_OP_NONE
#define _Operation_MAX Operation_OP_CLOSE
#define _Operation_ARRAYSIZE ((Operation)(Operation_OP_CLOSE+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ScheduleEntry_init_default               {false, 0, false, _WeekDay_MIN, false, _Operation_MIN, false, 0, false, 0}
#define Schedule_init_default                    {0, {{NULL}, NULL}}
#define ScheduleEntry_init_zero                  {false, 0, false, _WeekDay_MIN, false, _Operation_MIN, false, 0, false, 0}
#define Schedule_init_zero                       {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Schedule_version_tag                     1
#define Schedule_events_tag                      2
#define ScheduleEntry_enabled_tag                1
#define ScheduleEntry_wday_tag                   2
#define ScheduleEntry_op_tag                     3
#define ScheduleEntry_start_hou_tag              4
#define ScheduleEntry_start_min_tag              5

/* Struct field encoding specification for nanopb */
#define ScheduleEntry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UENUM,    wday,              2) \
X(a, STATIC,   OPTIONAL, UENUM,    op,                3) \
X(a, STATIC,   OPTIONAL, INT32,    start_hou,         4) \
X(a, STATIC,   OPTIONAL, INT32,    start_min,         5)
#define ScheduleEntry_CALLBACK NULL
#define ScheduleEntry_DEFAULT NULL

#define Schedule_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    version,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  events,            2)
#define Schedule_CALLBACK pb_default_field_callback
#define Schedule_DEFAULT NULL
#define Schedule_events_MSGTYPE ScheduleEntry

extern const pb_msgdesc_t ScheduleEntry_msg;
extern const pb_msgdesc_t Schedule_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ScheduleEntry_fields &ScheduleEntry_msg
#define Schedule_fields &Schedule_msg

/* Maximum encoded size of messages (where known) */
/* Schedule_size depends on runtime parameters */
#define ScheduleEntry_size                       28

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
