/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "schedule.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ScheduleEntry, ScheduleEntry, AUTO)


PB_BIND(Schedule, Schedule, AUTO)





