SKETCH = $(HOME)/Arduino/thermostat/thermostat.ino

UPLOAD_PORT = /dev/ttyUSB0
BOARD = generic
UPLOAD_SPEED = 115200
FLASH_MODE = qio
VERBOSE = 1

include $(HOME)/Arduino/makeEspArduino/makeEspArduino.mk
